name: Reusable workflow

on:
   workflow_call:
     inputs:
        app-dir:
          required: true
          type: string
        runner-name:
          required: true
          type: string
jobs:
  deploy:
    runs-on: ${{ inputs.run-name}}
    
    steps:
      - name: Declare Variables
        run: |
         echo "APP_DIR=${{app-dir}}" >> "$GITHUB_ENV"
         CAT $APP_DIR
