name: Reusable workflow

on:
  push:
    branches: [ dev ]
jobs:
  DEPLOY:
    runs-on: unit
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          path: dev

      - name: Declare Variables
        run: |
          cd dev
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"  
          echo "CURRENT_DIR=$APP_DIR/$(echo ${GITHUB_REF#refs/heads/})/repos/$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
