name: Reusable workflow

on:
   workflow_call:
     inputs:
        runner-name:
          required: true
          type: string
jobs:
  deploy:
    runs-on: ${{ inputs.runner-name}}
    
    steps:
      - name: Declare Variables
        run: |
         echo hello. world!
