name: Reusable workflow

on:
   workflow_call:
     inputs:
        runs-on:
          required: true
          type: string
        app-dir:
          required: true
          type: string
jobs:
  deploy:
    runs-on: ${{ inputs.runs-on}}
    
    steps:
      - name: Declare Variables
        run: |
         echo hello. world!
         cat ${{inputs.app-dir}}
